from typing import Any, overload

from ._types import DShape, DType

class RangeInfo:
    """Class to describe the range of data."""

    pos: tuple[int, int]
    data_shape: DShape
    dtype: DType
    strict: bool

    def __init__(self, pos: tuple[int, int], data_shape: DShape, *, dtype: DType = DType.Any, strict: bool = True) -> None: ...
    @property
    def start(self) -> tuple[int, int]: ...
    @property
    def end(self) -> tuple[int, int]: ...
    @property
    def shape(self) -> tuple[int, int]: ...

class ReadOnlyWorksheet:
    """Read-only worksheet class"""

    def read_value(self, range_info: RangeInfo) -> Any: ...
    @overload
    def read_values(self, range_info_list: list[RangeInfo]) -> list[Any]: ...
    @overload
    def read_values(self, range_info_list: dict[str, RangeInfo]) -> dict[str, Any]: ...
    def cell_value(self, cell_addr: tuple[int, int] | str, *, dtype: DType = DType.Any, strict: bool = True) -> Any: ...

class ReadOnlyWorkbook:
    """Read-only workbook class"""

    def __init__(self, path: str) -> None: ...
    def get_by_name(self, name: str) -> ReadOnlyWorksheet: ...
    def get_by_idx(self, idx: int) -> ReadOnlyWorksheet: ...
    def get(self, idx_or_name: int | str) -> ReadOnlyWorksheet: ...
    @property
    def sheetnames(self) -> list[str]: ...
    @property
    def worksheets(self) -> list[ReadOnlyWorksheet]: ...
    @overload
    def read_worksheets(self, worksheets_to_read: dict[str | int, list[RangeInfo]]) -> dict[str | int, list[Any]]: ...
    @overload
    def read_worksheets(self, worksheets_to_read: dict[str | int, dict[str, RangeInfo]]) -> dict[str | int, dict[str, Any]]: ...

@overload
def read_many(workbooks_to_read: dict[str, dict[int | str, list[RangeInfo]]]) -> dict[str, dict[int | str, list[Any]]]: ...
@overload
def read_many(workbooks_to_read: dict[str, dict[int | str, dict[str, RangeInfo]]]) -> dict[str, dict[int | str, dict[str, Any]]]: ...
